<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS005 - FeatureLogin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>995511ee-9f82-4bdb-aea5-b1cb65d5e7c6</testSuiteGuid>
   <testCaseLink>
      <guid>a5a7ceaf-95ee-40af-8ccf-f6400348312f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/WEB/SauceDemo/step_definition/user_login/Login004 - User want to login only username valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f924d0ed-c0eb-4c93-9a53-d53edce3db7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>918ee92b-d85d-4eba-a5e2-eb350e34731c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/WEB/SauceDemo/step_definition/user_login/Login003 - User want to login invalid credentials</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d59ec998-8706-4d82-a4ce-1f308e96ffb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eed99941-85b8-4dea-b3c9-bd2adf648744</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2cd21201-89fd-4aa9-b3f9-d3a0fbf5a82e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/WEB/SauceDemo/step_definition/user_login/Login002 - User want to login using correct credential</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75b4159c-fd7b-4ec1-a6fe-11090038fbb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a91fd0e-34c7-4f9d-81a3-8694c7911341</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64067071-9353-417f-9e93-403336ec0be7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/WEB/SauceDemo/step_definition/user_login/Login001 - User want to login without input username and password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddc5c278-b007-4f3e-8945-12b32798ef74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b4700ce-4b04-40c9-b08e-08e07fe7b640</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>078b8d79-60c7-4420-9ec5-48fd10005cf3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WEB/cucumber/Runner</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
