<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Back to products_inventory_details_img</name>
   <tag></tag>
   <elementGuidId>eff55d89-f595-4623-a060-2fe1fdaf35ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inventory_item_container']/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.inventory_details_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>284f8e84-a43a-45c0-8364-a1e5715dd084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sauce Labs Backpack</value>
      <webElementGuid>a0f05dd3-73df-4cdd-b4de-d0302e3aeb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_details_img</value>
      <webElementGuid>d734f824-f51d-4ed8-bf0a-8ae6e3fd0786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/sauce-backpack-1200x1500.34e7aa42.jpg</value>
      <webElementGuid>2a088d90-7376-4b89-aa16-8aa2fda42208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inventory_item_container&quot;)/div[@class=&quot;inventory_details&quot;]/div[@class=&quot;inventory_details_container&quot;]/div[@class=&quot;inventory_details_img_container&quot;]/img[@class=&quot;inventory_details_img&quot;]</value>
      <webElementGuid>b72ab1bc-cf92-4192-ba5a-ec0a72c801a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inventory_item_container']/div/div/div/img</value>
      <webElementGuid>b0e2614b-92b5-425d-986e-d7769de9b059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sauce Labs Backpack']</value>
      <webElementGuid>9bead673-006e-496b-8c73-65d7169cc075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>9f0b98e2-12bc-4d7f-b8f1-2d72f3b1773c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sauce Labs Backpack' and @src = '/static/media/sauce-backpack-1200x1500.34e7aa42.jpg']</value>
      <webElementGuid>1994e1b3-34f4-499b-a676-3ba01170ab1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
